global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']

  - job_name: 'ray'
    static_configs:
      - targets: ['ray-head:8265']

  - job_name: 'nomad'
    static_configs:
      - targets: ['nomad:4646']
